FROM --platform=linux/amd64 puppeteer:latest-dev
RUN npm install --location=global mocha \
    && wget --quiet https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh -O /usr/sbin/wait-for-it.sh \
    && chmod +x /usr/sbin/wait-for-it.sh

COPY integration-tests /integration-tests
