name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  # Build the image every Sunday
    - cron: '0 0 * * 0'

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    name: Build Image and Publish
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install Cosign
        uses: sigstore/cosign-installer@main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - id: docker_meta
        uses: docker/metadata-action@v3.6.0
        with:
          images: chimbosonic/puppeteer
          tags: |
            type=sha,format=long
            type=raw,value=14.1.1-latest
            type=raw,value=latest
          labels: |
            org.opencontainers.image.title=puppeteer
            org.opencontainers.image.description=Puppeteer is a headless Chrome Node.js API. 
            org.opencontainers.image.authors=Alexis Lowe <alexis.lowe@protonmail.com>
            org.opencontainers.image.documentation=https://github.com/chimbosonic/puppeteer-container/blob/main/README.md
            org.opencontainers.image.url=https://hub.docker.com/r/chimbosonic/puppeteer
          
      - name: Build and Push container images
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          load: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
      
      - name: Test
        run: |
          make -C tests build-test
          make -C tests run-test
          ls tests/screenshots/app.png
          exit 123

      - uses: actions/upload-artifact@v1
        with:
          name: test-screenshot.png
          path: tests/screenshots/app.png

      - name: Build and Push container images
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

      - name: Write signing key to disk (only needed for `cosign sign --key`)
        run: echo "${{ secrets.COSIGN_KEY }}" > cosign.key

      - name: Sign image with signing key
        run: cosign sign --key cosign.key -a "repo=${{ github.repository }}" -a "workflow=${{ github.workflow }}" -a "ref=${{ github.sha }}" ${TAGS}
        env:
          TAGS: ${{ steps.docker_meta.outputs.tags }}
          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSWORD}}